
version: '3.8'

services:
  api:
    build:
      target: development
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./api:/app
    depends_on:
      - client

  client:
    build:
      target: development
      context: ./client
    ports:
      - "3006:3006"
    volumes:
      - ./client:/app
